[package]
name = "smartplug"
version = "0.1.0"
authors = ["Åke Amcoff <ake.amcoff@lynx.agency>"]
edition = "2018"
description = "A small package for controlling smart outlets."
license = "MIT"

[dependencies]